apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: 
          volumeMounts:
            - name: standard-volume
              mountPath: /k8_assignment
      volumes:
        - name: standard-volume
          persistentVolumeClaim:
            claimName: pvc-volume